version: '3.8'

services:
  vscode:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    privileged: true
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
  # (Adding the "ports" property to this file will not forward from a Codespace.)
  
  api:
    build:
      context:  .
      dockerfile: Dockerfile.server
    restart: unless-stopped
    volumes:
      - ./server.yaml:/config/server.yaml:ro
      - ./server-entry.sh:/entrypoint.sh

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
