name: dev ci

on:
    push:
        branches: ['main']
    workflow_dispatch:

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - run: sudo -E nextjs-deploy .
              env:
                  URL: ${{ secrets.URL }}
                  NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
